language: scala
jdk: oraclejdk8
scala:
  - 2.11.8
services:
  - docker
script:
  - sbt clean compile docker:publishLocal
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push faiaz/course_work;
    fi
