language: scala
jdk: oraclejdk8
scala:
- 2.11.8
services:
  - docker
script:
- sbt clean compile
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    sbt docker:publish
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push faiaz/scalastics:latest;
    fi
